
server:
  port: 8071

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/test
  application:
    main:
      allow-bean-definition-overriding: true
    name: CustomerService
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1